
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module random(

	//////////// LED //////////
	input 				clk,
	output		     [3:0] ran,
	input pause
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg [3:0] count, c_count;
//=======================================================
//  Structural coding
//=======================================================
always@(*)begin
	if(pause ==1'b1) begin
		c_count=count;
	end
	else begin
		c_count=count+1;
	if(count==4'b1010) begin
		c_count=4'b0000;
	end
end
end
always @(posedge clk) begin
	count<=c_count;
end
assign ran=count;
endmodule
