
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module remapper(

	//////////// CLOCK //////////
	input 		[15:0] s,
	//////////// SW //////////
	output wire  [9:0] led,
	output wire [9:0]	place,
	input 			enable,
	input ran,
	input [3:0] random 
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
reg [9:0] out;
reg [15:0] smooth;
always @(*) begin
if(ran ==1'b1) begin
	if(random==4'b0000) 
		out=10'b00_0000_0001;
	else if (random==4'b0001)
		out=10'b00_0000_0010;
	else if (random==4'b0010)
		out=10'b00_0000_0100;
	else if (random==4'b0011)
		out=10'b00_0000_1000;
	else if (random==4'b0100)
		out=10'b00_0001_0000;
	else if (random==4'b0101)
		out=10'b00_0010_0000;
	else if (random==4'b0110)
		out=10'b00_0100_0000;
	else if (random==4'b0111)
		out=10'b00_1000_0000;
	else if (random==4'b1000)
		out=10'b01_0000_0000;
	else if (random==4'b1001)
		out=10'b10_0000_0000;
end 
else begin
if(enable ==1'b0) begin
	out=10'b00_0000_0000;
end
else begin
if(s[15]==1'b1) begin
	smooth=16'h8000-s[14:0];
	if(smooth >=80)
	out=10'b00_0000_0001;
	else if(smooth < 80 && smooth >=60)
	out=10'b00_0000_0010;
	else if(smooth <60 && smooth >=40)
	out=10'b00_0000_0100;
	else if(smooth <40 && smooth >=20)
	out=10'b00_0000_1000;
	else if(smooth <20 && smooth >=0)
	out=10'b00_0001_0000;
end
else begin
	smooth=s;
	if(smooth >=0 && smooth <=20)
	out=10'b00_0010_0000;
	else if(smooth >20 && smooth <=40)
	out=10'b00_0100_0000;
	else if(smooth >40 && smooth <=60)
	out=10'b00_1000_0000;
	else if(smooth >60 && smooth <=80)
	out=10'b01_0000_0000;
	else if(smooth > 80 )
	out=10'b10_0000_0000;
	end
end
end
end
assign led=out;
assign place=out;
endmodule
