
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module timer(
	input 			    	clk,
	output wire [11:0]   out,
	input 					enable,
	input 					reset,
	input 					set,
	output 	wire			done
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
reg [9:0] count;
reg [9:0] c_count;
reg done1; 


//=======================================================
//  Structural coding
//=======================================================
always @(*) begin
	done1=1'b0;
//else begin
	if(enable==1'b1) begin
		c_count=count + 1;
	if(count==10'b1111100111) begin
		c_count=10'b1111100111;
		done1=1'b1;
	end
 end
 if((reset==1'b0)||(set==1'b1)) begin
		c_count=10'b0000_0000_00;
	end
end
//end
always @(posedge clk) begin 
		count<=c_count;
end 

assign out=count;
assign done =done1;
endmodule
